### ISSUE TITLE
0X1218 works as a Trackpad but has point moving problems

### ISSUE THREAD

**Issue by laelsirus** [blankmac/AlpsT4USB#4]
Thank you for your efforts!

I'm using the Latitude 5290 2-in-1 and the touchpad ID is Alps 044E 1218.
The touch screen worked as a trackpad, and the touchpad recognized as a 2-point scrollable mouse.

With your source code of your last release (1.3 version), I modifed value that is '#define HID_PRODUCT_ID_T4_USB 0X1216' 
 to '0X1218' and the touchpad has been started works as a trackpad.
(VoodooI2C.kext, VoodooI2CHID.kext, AlpsT4USB is in /L/E)
But the mouse point was so fast that it seemed to be random movement (I think I was caught in polling mode)

Do you have any ideas for solving this?

If you need more information, here is my efi.
https://github.com/laelsirus/Dell-Latitude-5290-2-in-1-CLOVER

Thanks.

**Comment by blankmac** [comment]
Really couldn't say what is happening without seeing your ioreg & kextstat output.
Also, be aware that if you are building from the latest source, this kext has transitioned to using VoodooInput so you will need that loaded as well.

**Comment by laelsirus** [comment]
Thank you for your reply.
I tried both the last commit version and the last release version.
I knew that VoodooInput was included in the last commit source, and I added the source and built it.
The results were the same.
I am currently trying with the last release version.

Here are the data before and after using the AlpsT4USB. (IOREG, Kextstat)

[laelsirus_AlpsT4USB.zip](https://github.com/blankmac/AlpsT4USB/files/4395175/laelsirus_AlpsT4USB.zip)

**Comment by blankmac** [comment]
There is no need to use the Alps USB kext, your touchpad device supports the Windows precision touchpad protocol which is already baked into VoodooI2CHID.  The Alps kext utilizes a vendor defined protocol which does not work with your device.  Add the USB transport to the VoodooI2CHID info.plist and you should get a working touchpad.  If not, the appropriate forum to seek help is here -- https://gitter.im/alexandred/VoodooI2C
