### ISSUE TITLE
How do I to determine device's ID?

### ISSUE THREAD

**Issue by ettingshausen** [blankmac/AlpsT4USB#5]
>The latest release of this kext should also work for I2C Alps touchpad devices with the following device IDs - 0x1209, 0x120b, 0x120c but it is currently untested.   

I installed the VoodooI2C text with the official guide, trackpad (Alps) worked and it support two fingers gesture, but does't show in Settings.   
I want to try this one, but I don't know how to determine it's ID.  It seems `getProductID` function which provide by the macOS SDK will get it's ID, still have no idea. Using IORegistryExplorer ?
Please provide a guide.

**Comment by ettingshausen** [comment]
I add a line before `switch` in `AlpsT4USBEventDriver::handleStart` method. It print product id which is `4638 (0x121E)`.  It returned `false`.
```c++
    IOLog("AlpsT4USB get product id: (%d)\n", hid_interface->getProductID());
    switch (hid_interface->getProductID()) {
            
        case HID_PRODUCT_ID_T4_USB:
        case HID_PRODUCT_ID_G1:
            dev_type = T4;
            break;
        case HID_PRODUCT_ID_U1:
        case HID_PRODUCT_ID_U1_DUAL:
            dev_type = U1;
            break;
            
        default:
        {   hid_interface = NULL;
            return false;
        }
     }
``` 
And a TIMEOUT log appeared in system log. 
```
2020-04-06 09:45:47.656937+0800  localhost kernel[0]: (kernel) VoodooI2CSensorHubEnabler::INT33D0 Enabled Sensor Hub
2020-04-06 09:45:47.669938+0800  localhost kernel[0]: (kernel) VoodooGPIOSunrisePointLP::Registering hardware pin 56 for GPIO IRQ pin 56
2020-04-06 09:45:47.671853+0800  localhost kernel[0]: (kernel) VoodooI2CHIDDevice::AUI165B Timeout waiting for device to complete host initiated reset
```

**Comment by blankmac** [comment]
Ok, a few things.  You answered your own question, the device ID is 0x121e.  You can try adding it in the header but this kext as it is currently written has been shown to not work for I2C Alps devices.  Additionally, if you are building from the current source, you will need the latest version of VoodooInput from the acidanthera repo.

**Comment by ettingshausen** [comment]
👌，I'll try add the header later. 
By the way, trackpad doesn't show in Setting is it the problem of ALPS?
I am stuck here, I know this question is should not be asked here, but ... any information may help me to work it out.

**Comment by blankmac** [comment]
Not typically.  But again, you aren't likely to get it working for an I2C version of the Alps touchpad.  Don't forget that you will also need VoodooInput if you are building from the latest source.
