### ISSUE TITLE
one question about AlpsT4USB ?

### ISSUE THREAD

**Issue by lugokeT** [blankmac/AlpsT4USB#6]
Hello Blankmac,

is it possible for HP Elite X2 G3 Series ? 
I have an Alps Touchpad with  Product ID:	0x1221 & Vendor ID:	0x044e. 
Until now I could not get it to work for gestures under Mojave 10.14.1.

Regards

**Comment by blankmac** [comment]
You can try adding your product ID here -

https://github.com/blankmac/AlpsT4USB/blob/0feb0f2d21fd9f5edabe09de1e83a0fe5933123c/AlpsT4USB/AlpsT4USB.hpp#L42

And then add to the product id initialization here -

https://github.com/blankmac/AlpsT4USB/blob/0feb0f2d21fd9f5edabe09de1e83a0fe5933123c/AlpsT4USB/AlpsT4USB.cpp#L137

If it works let me know and I'll add it in.

**Comment by lugokeT** [comment]
Hello blankmac,

unfortunately I have no skills to change because of missing knowlegde and Xcode is not installed on my system to make an executable from this .hpp file. 

Could you please send me a finished kext Release with my Product ID 0x1221 ? 
After that I would give you a feedback if that works.

Regards

**Comment by blankmac** [comment]
[Alps-t4-0x1221.zip](https://github.com/blankmac/AlpsT4USB/files/5846815/Alps-t4-0x1221.zip)

Here you go, you'll need the latest version of VoodooI2C / VoodooI2CHID as well.

**Comment by lugokeT** [comment]
Hello again,

today i test it with newest voodooi2c driver and install it with hackintool to /library/extensions. After boot up unfortunately it does not work. Only touch screen working with gestures but trackpad will not work.
My Trackpad is only working with karabiner i disable karabiner,too but nothing changed.

In Hackintool i get this error: 

"AlpsT4USB.kext/ -- file:///Library/Extensions/", ID = "com.blankmac.AlpsT4USB" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fe445313310 [0x7fff896068f0]> { URL = "X86PlatformPlugin.kext/ -- file:///System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/", ID = "com.apple.driver.X86PlatformPlugin" }
Invalid signature -67050 for kext <OSKext 0x7fe44579b5a0 [0x7fff896068f0]> { URL = "VoodooInput.kext/ -- file:///Library/Extensions/VoodooI2C.kext/Contents/PlugIns/", ID = "me.kishorprins.VoodooInput" }
Invalid signature -67050 for kext <OSKext 0x7fe445776b70 [0x7fff896068f0]> { URL = "AlpsT4USB.kext/ -- file:///Library/Extensions/", ID = "com.blankmac.AlpsT4USB" }
kxld[com.blankmac.AlpsT4USB]: The super class vtable 'vtable for IOHIDEventService' for vtable 'vtable for AlpsT4USBEventDriver' is out of date. Make sure your kext has been built against the correct headers.
Link failed (error code 5).
Prelink failed for com.blankmac.AlpsT4USB; omitting from prelinked kernel.
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fbb47b64740 [0x7fff896068f0]> { URL = "X86PlatformPlugin.kext/ -- file:///System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/", ID = "com.apple.driver.X86PlatformPlugin" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fbb47f52420 [0x7fff896068f0]> { URL = "AlpsT4USB.kext/ -- file:///Library/Extensions/", ID = "com.blankmac.AlpsT4USB" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbb47f58860 [0x7fff896068f0]> { URL = "VoodooI2CHID.kext/ -- file:///Library/Extensions/", ID = "com.alexandred.VoodooI2CHID" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbb47f69f60 [0x7fff896068f0]> { URL = "VoodooI2C.kext/ -- file:///Library/Extensions/", ID = "com.alexandred.VoodooI2C" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbb47f6b5b0 [0x7fff896068f0]> { URL = "VoodooGPIO.kext/ -- file:///Library/Extensions/VoodooI2C.kext/Contents/PlugIns/", ID = "org.coolstar.VoodooGPIO" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbb47f75950 [0x7fff896068f0]> { URL = "VoodooI2CServices.kext/ -- file:///Library/Extensions/VoodooI2C.kext/Contents/PlugIns/", ID = "com.alexandred.VoodooI2CServices" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fbb47f76070 [0x7fff896068f0]> { URL = "VoodooInput.kext/ -- file:///Library/Extensions/VoodooI2C.kext/Contents/PlugIns/", ID = "me.kishorprins.VoodooInput" }

Regards

**Comment by blankmac** [comment]
Weird.  I just tested it with VoodooI2C 2.6.1 and it is working fine on Big Sur with OC.  I'll attach all 3 for you to try.  No need to put it in /L/E.  Should work injected with either Clover or OC.

[VoodooI2C-Alps.zip](https://github.com/blankmac/AlpsT4USB/files/5852038/VoodooI2C-Alps.zip)


** Edit -- Turns out there was a change in the MacKernel SDK that caused the issue.  I've corrected it in the new release but it doesn't have your device ID.  If you can confirm that it works with the above (VoodooI2C 2.6.1), I'll add it into the next release.

**Comment by blankmac** [comment]
Closed for inactivity.  If you can confirm that Alps / voodooi2c kexts in my previous post work for you then I’ll add your device ID.

**Comment by lugokeT** [comment]
Hello Blankmac again,

i switched from Clover to OC and now Touchpad is working fine with older Kext so the integration of my product ID was not necessary.

Sorry for late answer and thanks a lot for such a great kext.

Regards
