### ISSUE TITLE
Thumb not continuously detected when Index finger placed first

### ISSUE THREAD

**Issue by frickingphil** [blankmac/AlpsT4USB#7]
Hi, first off thank you for this awesome driver, it's been rock solid on my G2. 

Unfortunately **there seems to be an issue with the way thumb detection is being handled.** I've attached a video demonstrating the behavior as well as how it's supposed to be working.

When a finger gets placed on the trackpad and the thumb after it, the thumb is filtered correctly and does not affect cursor position or gestures...however the moment the finger is lifted, the thumb's touch point also disappears. **This breaks dragging using the physical button, as the thumb's touch point needs to stay active for the physical button's hold to remain registered.**

This leads to frustrating behavior like items in the OS being dropped wherever your index finger lifted, not where you were intending to drop them, or quick transitions between pointing the cursor with the index finger, lifting it, and then clicking with the thumb not registering any clicks at all until the thumb is lifted and then re-placed on the trackpad.

In my video example, I use the selection box on the desktop to show the behavior: the moment i reposition my index finger, the selection box disappears, despite my thumb still touching the trackpad and also holding the physical click down. I then repeat the bug with touches only (no clicks) to show that it occurs even without the physical button being involved...in the [FingerMgmt](https://github.com/jnordberg/FingerMgmt) window you can see the thumb's touch point disappear when i lift my index finger.

The machine serving as a control test is a Surface Pro 4, also running VoodooInput for its touchpad. Another hackintosh I've tested behaves the same way.

At first I thought it was a conflict with the touchscreen, so I disabled the ACPI patches for it so it wouldn't be found by VoodooInput, leaving the trackpad as the only device using it, but behavior was unchanged.

I'm using the latest releases of all software involved.

Hopefully this is enough info for you to diagnose!

https://user-images.githubusercontent.com/17838533/106406096-16738300-63ed-11eb-83d2-b466eb0d4c2e.mp4

**Comment by blankmac** [comment]
Can you please attach the output of "kextstat" in a text file?

**Comment by frickingphil** [comment]
Hi, thanks for quick response! Here ya go. 

[kextstatoutput.txt](https://github.com/blankmac/AlpsT4USB/files/5908043/kextstatoutput.txt)

**Comment by blankmac** [comment]
Seems you're using version 1.0 of the Alps Kext.  Please try 1.4 -- https://github.com/blankmac/AlpsT4USB/releases/tag/1.4

**Comment by frickingphil** [comment]
<img width="480" alt="Screen Shot 2021-02-01 at 6 08 34 PM" src="https://user-images.githubusercontent.com/17838533/106542386-97e41780-64b8-11eb-9635-56d67da93aa5.png">

This is the kext in my OC folder...I re-downloaded 1.4 from your link and the file sizes are the exact same down to the byte as well. Looks like it was built Jan 25th.

EDIT: for what it's worth, I just checked the Info.plist and CFBundleVersion says "1" while CFBundleShortVersionString says "1.4"

**Comment by blankmac** [comment]
Ah gotcha, my mistake.  Hmmm, well, I guess I'd like to rule out the recent change adding in the thumb.  I'm not at home at the moment but I'll upload something for you later tonight to test whenever you get the chance.  I no longer have any laptop hacks so I'm not able to confirm / fix the problem myself unfortunately.

**Comment by frickingphil** [comment]
No worries! Sounds good, I'm willing to give you all the debug info I can, just let me know what you need.

**Comment by blankmac** [comment]
The attached is with the thumb detection routine removed.  There's also the possibility that the rudimentary palm rejection is what is causing the problem.  Let me know how it goes.

[T4-nothumbdetection.zip](https://github.com/blankmac/AlpsT4USB/files/5915299/T4-nothumbdetection.zip)

**Comment by frickingphil** [comment]
Alright, so I tried the "no thumb detection" version and didn't see any behavioral changes regarding the finger placement bug, the only thing I noticed was that the thumb was now able to affect the cursor position more easily vs. the vanilla 1.4 kext.

But it made me realize that the finger placement bug actually affects _all fingers_, not just the thumb...I reverted back to vanilla 1.4 and tested it, and here's a new clip of the behavior. Notice that it removes both touch points whenever the 1st of any 2 fingers placed on the trackpad are removed. 

The thumb might be a red herring at this point...

https://user-images.githubusercontent.com/17838533/106704547-2c29a980-65a1-11eb-94ed-26fa6dfc4638.mp4

**Comment by frickingphil** [comment]
Testing with multiple fingers shows that it seems to always affect whichever the last finger placed down was, no matter the order. You can see it affecting my index finger in one clip, and then I test with the middle finger placed last, and it affects it the same.

Note that this is with vanilla 1.4 again. Surface Pro 4 is a control test showing expected behavior.

https://user-images.githubusercontent.com/17838533/106705700-4b293b00-65a3-11eb-8dd7-f8f36e94dfc8.mp4

https://user-images.githubusercontent.com/17838533/106705593-1e752380-65a3-11eb-9fd2-8f991600aa1b.mp4

https://user-images.githubusercontent.com/17838533/106705586-1a490600-65a3-11eb-8849-38843b82c116.mp4

**Comment by blankmac** [comment]
Thanks for all the details.  Seems like it's probably something in my logic.  I'll have to think on it a bit.

**Comment by frickingphil** [comment]
No worries, if I can help any further just let me know.

**Comment by blankmac** [comment]
Please give this a try when you get a chance.

[T4contact_count_fix.zip](https://github.com/blankmac/AlpsT4USB/files/5929492/T4contact_count_fix.zip)

**Comment by frickingphil** [comment]
Heyyyy, there it is! **Looks like touches and dragging are working as they should!**

**Comment by blankmac** [comment]
Nice!  Thanks for reporting / testing.  I'll mark this closed.  Feel free to reopen if needed.
