### ISSUE TITLE
Regarding plans to integrate ALPS U1 support

### ISSUE THREAD

**Issue by ghost** [blankmac/AlpsT4USB#8]
Hi,

First of all, thank you so much for your hard work on this project! I found the reason for this kext not supporting Alps I2C-based touchpads, according to the [Linux original driver](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-alps.c). There seems like to be three ALPS HID touchpad models, T3 (PS2?), U1 (I2C, Trackpad uses either PTP or vendor specific protocol, and Dual pointing uses vendor specific protocol) and T4. The U1 model is the ALPS I2C touchpad/ dual pointing that [HP and Dell uses](https://wiki.gentoo.org/wiki/Dell_Latitude_5495). I wonder if you have plans to integrate U1 support into this kext. Many thanks in advance!

Edit: For reference, the current support status for Alps U1 solutions is a half-working trackpad (trackpad itself works using VoodooI2CHID, only left touchpad button works and it is only activated when there is an active finger detected on the trackpad, middle and right touchpad buttons don't work; I2C trackpoint doesn't work at all). Thanks again!

Edit 2: Ok, I'm now kind of beginning to understand the problem. So the code for U1 is indeed ported to this kext, however, for some reason it just doesn't work. I'll be more than happy to provide you any debugging logs to maybe debug the problem if you are interested in fixing the U1 support. Otherwise please just close this issue and ignore my ignorance. Thank you!

**Comment by blankmac** [comment]
Unfortunately I don't have the hardware to test and am not quite "dev enough" to fix the problem blind.  All of the info is there tho for someone who is savvy to take the U1 initialization and align it to the Elan.  I think that could work.

**Comment by ghost** [comment]
Thank you for your reply!

**Comment by Lorys89** [comment]
hello, I have a dell Latitude e7280 with i2c alps, on big sur works with i2c and i2c hid, but on system preferences trakpad section is not found, and the gestures do not work, the 2 keys under the trakpad work, I am available for tests if you make this kext compatible 
Thank you

**Comment by juico** [comment]
Hey, I got the Alps T4(120c) touchpad working on my zbook g3 studio with multi finger gestures. I will try to put the code in a fork for other people to try out. 

The problem seemed to be that the linux driver added the report_id to the beginning of the report and would take it out samewhere further up in the api. The voodooI2CHID didnt seem to do this so by removing the report_id from the beginning of the report the touchpad does init properly. Probaly the  fix will work for the U1 version aswell.

**Comment by Lorys89** [comment]
> Hey, I got the Alps T4(120c) touchpad working on my zbook g3 studio with multi finger gestures. I will try to put the code in a fork for other people to try out.
> 
> The problem seemed to be that the linux driver added the report_id to the beginning of the report and would take it out samewhere further up in the api. The voodooI2CHID didnt seem to do this so by removing the report_id from the beginning of the report the touchpad does init properly. Probaly the fix will work for the U1 version aswell.

waiting to try, I have i2c alps u1 dual 120b

**Comment by juico** [comment]
[AlpsT4USB.kext.zip](https://github.com/blankmac/AlpsT4USB/files/7238358/AlpsT4USB.kext.zip)
You can try this file, you also need the voodooi2c and voodooi2chid kexts to get it working.  Make sure you have way to disable or delete the kext because it might give a kernel panic.

**Comment by Lorys89** [comment]
> [AlpsT4USB.kext.zip](https://github.com/blankmac/AlpsT4USB/files/7238358/AlpsT4USB.kext.zip)
> You can try this file, you also need the voodooi2c and voodooi2chid kexts to get it working. Make sure you have way to disable or delete the kext because it might give a kernel panic.
[i2cLog.log](https://github.com/blankmac/AlpsT4USB/files/7238486/i2cLog.log)
[alpst4Log.log](https://github.com/blankmac/AlpsT4USB/files/7238487/alpst4Log.log)

![Schermata 2021-09-27 alle 20 28 38](https://user-images.githubusercontent.com/64613690/134965227-3542fc48-b99e-418c-899c-d8b1542851ea.png)
[MacBook Pro di Admin.zip](https://github.com/blankmac/AlpsT4USB/files/7238488/MacBook.Pro.di.Admin.zip)
but not work touchpad :(

**Comment by blankmac** [comment]
> Hey, I got the Alps T4(120c) touchpad working on my zbook g3 studio with multi finger gestures. I will try to put the code in a fork for other people to try out.
> 
> The problem seemed to be that the linux driver added the report_id to the beginning of the report and would take it out samewhere further up in the api. The voodooI2CHID didnt seem to do this so by removing the report_id from the beginning of the report the touchpad does init properly. Probaly the fix will work for the U1 version aswell.

First, glad you were able to get it working, but I'm not sure I understand what you mean exactly.  The report id isn't a part of the initialization process, but certainly does appear in the input report.  Can you link me to your changes?  Thx.

**Comment by Lorys89** [comment]
@juico please update your fork with the latest changes so that we can understand and help.

**Comment by juico** [comment]
Sorry i was bit busy and inexperienced with github so it took a longer. I uploaded the latest changes to my fork.

**Comment by Lorys89** [comment]
join https://gitter.im/AlpsT4USB-TEST-Room/community  
kext test and development room, please join.
@juico  @blankmac @lulu-gh

**Comment by kprinssu** [comment]
Please do not ping me on random projects. I am unable to help as I am very busy.

**Comment by juico** [comment]
I will close this issue as the [AlpsHID](https://github.com/blankmac/AlpsHID) driver now supports U1 touchpads.
